steps:

# Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'asia-south2-docker.pkg.dev/cicd-tutorial-497406/cicd-repo/fashionhub:$SHORT_SHA'
    - '.'

# Push image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'asia-south2-docker.pkg.dev/cicd-tutorial-497406/cicd-repo/fashionhub:$SHORT_SHA'

# Deploy Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'fashionhub'
    - '--image'
    - 'asia-south2-docker.pkg.dev/cicd-tutorial-497406/cicd-repo/fashionhub:$SHORT_SHA'
    - '--region'
    - 'asia-south2'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--port'
    - '8080'
    - '--vpc-connector'
    - 'cloud-run-to-mysql-server'

images:
- 'asia-south2-docker.pkg.dev/cicd-tutorial-497406/cicd-repo/fashionhub:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
