steps:

# Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'us-central1-docker.pkg.dev/cicd-tutorial-497406/cicd-repo/myapp:$SHORT_SHA'
    - '.'

# Push Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'us-central1-docker.pkg.dev/cicd-tutorial-497406/cicd-repo/myapp:$SHORT_SHA'

# Deploy to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'myapp'
    - '--image'
    - 'us-central1-docker.pkg.dev/cicd-tutorial-497406/cicd-repo/myapp:$SHORT_SHA'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--port'
    - '80'
    - '--service-account'
    - 'cicd-124@cicd-tutorial-497406.iam.gserviceaccount.com'

images:
- 'us-central1-docker.pkg.dev/cicd-tutorial-497406/cicd-repo/myapp:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
